# Generated by Django 2.2 on 2019-05-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190511_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.IntegerField(null=True),
        ),
    ]
